// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qubvigjcgcfrrdfkiloe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1YnZpZ2pjZ2NmcnJkZmtpbG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDEyNjQsImV4cCI6MjA2NzU3NzI2NH0.eA4PA_QlhS9D04jm57gIlsA97vDHWWKQZ-JOqynTepY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});