// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

if (!SUPABASE_URL || SUPABASE_URL === 'https://your-project-id.supabase.co') {
  console.warn(
    '[Supabase] VITE_SUPABASE_URL is not set. ' +
    'Add your project URL to .env.local to enable database features.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL ?? 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY ?? 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (...args) => {
        const url = String(args[0]);
        if (url.includes('placeholder.supabase.co')) {
          return Promise.reject(new Error('Supabase not configured'));
        }
        return fetch(...args);
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);
