// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqjgfmpvvtprviptioei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxamdmbXB2dnRwcnZpcHRpb2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTI2NTQsImV4cCI6MjA2NzY4ODY1NH0.TVDORxOPv44-N1z2F2P_HGgUvR8Pq2KggxVljPQ2_vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});